/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: "rgb(var(--ink) / <alpha-value>)",
        muted: "rgb(var(--muted) / <alpha-value>)",
        line: "rgb(var(--line) / <alpha-value>)",
        paper: "rgb(var(--paper) / <alpha-value>)",
        wash: "rgb(var(--wash) / <alpha-value>)",
        teal: { DEFAULT: "#0d9488" },
        up: "rgb(var(--up) / <alpha-value>)",
        down: "rgb(var(--down) / <alpha-value>)",
        warn: "rgb(var(--warn) / <alpha-value>)",
        "on-surface-variant": "#b9cacb",
        "secondary": "#70ffba",
        "primary": "#dbfcff",
        "on-primary": "#00363a",
        "surface-container-lowest": "#0a0e17",
        "tertiary-fixed-dim": "#4edea3",
        "error": "#ffb4ab",
        "on-secondary-container": "#00613e",
        "on-primary-fixed-variant": "#004f54",
        "on-secondary": "#003822",
        "secondary-fixed": "#4dffb2",
        "surface-variant": "#31353f",
        "on-tertiary-container": "#006d4a",
        "on-secondary-fixed-variant": "#005234",
        "inverse-on-surface": "#2c303a",
        "inverse-primary": "#006970",
        "on-secondary-fixed": "#002112",
        "surface-container": "#1c1f29",
        "on-primary-container": "#006970",
        "surface-container-highest": "#31353f",
        "on-background": "#dfe2ef",
        "on-primary-fixed": "#002022",
        "on-tertiary": "#003824",
        "on-tertiary-fixed": "#002113",
        "tertiary": "#d8ffe7",
        "surface-dim": "#0f131c",
        "surface-container-low": "#181b25",
        "tertiary-fixed": "#6ffbbe",
        "outline": "#849495",
        "secondary-container": "#01e599",
        "surface": "#0f131c",
        "on-surface": "#dfe2ef",
        "primary-container": "#00f0ff",
        "secondary-fixed-dim": "#00e297",
        "background": "#0f131c",
        "on-tertiary-fixed-variant": "#005236",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dfe2ef",
        "outline-variant": "#3b494b",
        "surface-bright": "#353943",
        "error-container": "#93000a",
        "primary-fixed": "#7df4ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "gutter": "0.5rem",
        "space-xl": "1.5rem",
        "margin": "0.75rem",
        "space-md": "0.75rem",
        "gutter-desktop": "0.75rem",
        "space-lg": "1rem",
        "margin-desktop": "1.25rem",
      },
      fontFamily: {
        display: ['"Caacupe One"', "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "data-micro": ["JetBrains Mono"],
        "data-metric": ["JetBrains Mono"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-caps": ["JetBrains Mono"],
        "label-md": ["Inter"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "data-tabular": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "headline-xl": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
      },
      fontSize: {
        metric: ["1.375rem", { lineHeight: "1.75rem", fontWeight: "650" }],
        "headline-lg-mobile": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", letterSpacing: "-0.011em", fontWeight: "400" }],
        "data-micro": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.02em", fontWeight: "400" }],
        "data-metric": ["1.5rem", { lineHeight: "1.75rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-caps": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-md": ["0.8125rem", { lineHeight: "1rem", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-xl-mobile": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-tabular": ["0.8125rem", { lineHeight: "1.125rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-sm": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0em", fontWeight: "400" }],
        "headline-xl": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-lg": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "-0.006em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
